apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sleeper-cert
  namespace: closed-services
spec:
  secretName: sleeper-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: cluster.koozu.fi
  dnsNames:
    - cluster.koozu.fi
