apiVersion: v1
kind: Service
metadata:
  name: sleeper
  namespace: sleeper-test
  labels:
    app: sleeper
spec:
  selector:
    app: sleeper
  ports:
    - name: web
      port: 8080
      targetPort: 8080
