apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-values
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/discord-bot-sleeper/argocd-apps.git
    targetRevision: HEAD
    path: "traefik-values"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
