apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: argocd
spec:
  destination:
    namespace: closed-services
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/discord-bot-sleeper/argocd-apps.git"
    path: "sleeper-manifests"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
