apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: nginx-test
spec:
  entryPoints:
    - web # Define the entry point (e.g., web, websecure)
  routes:
    - match: Host(`nginx.cluster.koozu.fi`) # Replace with your actual domain
      kind: Rule
      services:
        - name: nginx # Name of your NGINX service
          port: 80 # Port on which the NGINX service is exposed
